# Generated by Django 4.2.6 on 2023-10-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0002_location_unit_mesure_remove_measurement_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit_mesure",
            name="description",
            field=models.CharField(default="sgds", max_length=255),
            preserve_default=False,
        ),
    ]
