# Generated by Django 4.2.6 on 2023-11-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_rename_longtitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(choices=[('temp', 'Temperature'), ('feels_like', 'Temperature Feels Like'), ('temp_min', 'Temperature Min'), ('temp_max', 'Temperature Max'), ('pressure', 'Pressure'), ('humidity', 'Humidity'), ('wind_speed', 'Wind Speed'), ('wind_deg', 'Wind Direction'), ('rain_1h', 'Rainfall in the Last Hour'), ('snow_1h', 'Snowfall in the Last Hour'), ('clouds_all', 'Cloud Coverage'), ('weather_main', 'Weather Main')], max_length=255),
        ),
    ]
