# Generated by Django 4.2.6 on 2023-10-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0003_unit_mesure_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="altitude",
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="logtitude",
            field=models.CharField(max_length=255),
        ),
    ]
