# Generated by Django 4.2.6 on 2023-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0004_remove_location_altitude_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timestamps",
            name="date",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timestamps",
            name="time",
            field=models.TimeField(),
        ),
    ]
