# Generated by Django 4.2.6 on 2023-10-21 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0006_remove_timestamps_date_alter_timestamps_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="timestamps",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timestamps",
            name="time",
            field=models.TimeField(),
        ),
    ]
