# Generated by Django 4.2.6 on 2023-10-21 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0009_timestamps_date_timestamps_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timestamps",
            name="date",
        ),
        migrations.RemoveField(
            model_name="timestamps",
            name="time",
        ),
    ]
