# Generated by Django 4.2.6 on 2023-10-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0010_remove_timestamps_date_remove_timestamps_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="timestamps",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="timestamps",
            name="time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
